export default [
    [//I
        [false,false,false,false,false],
        [false,false,false,false,false],
        [false,true,true,true,true],
        [false,false,false,false,false],
        [false,false,false,false,false],
    ],
    [//L
        [true,false,false],
        [true,true,true],
        [false,false,false]
    ],
    [//J
        [false,false,true],
        [true,true,true],
        [false,false,false]
    ],
    [//O
        [false,true,true],
        [false,true,true],
        [false,false,false]
    ],
    [//S
        [false,true,true],
        [true,true,false],
        [false,false,false]
    ],
    [//Z
        [true,true,false],
        [false,true,true],
        [false,false,false]
    ],
    [//T
        [false,true,false],
        [true,true,true],
        [false,false,false]
    ]
];